name: "BoonMoSa"
backend: "python"
max_batch_size: 0

input [
  {
    name: "images__0"
    data_type: TYPE_FP32
    dims: [1, 3, 640, 640]
  }
]

output [
  {
    name: "output__0"
    data_type: TYPE_FP32
    dims: [1, 25200, 38]
  }
]

output [
  {
    name: "output__1"
    data_type: TYPE_FP32
    dims: [1, 32, 160, 160]
  }
]

instance_group [
    {
        kind: KIND_MODEL
        count: 1
    }
]
parameters: {key: "COMPILED_MODEL", value: {string_value: "/model-repository/BoonMoSa/1/model_neuron.pt"}} 
parameters: {key: "NEURON_CORE_START_INDEX", value: {string_value: "0"}} 
parameters: {key: "NEURON_CORE_END_INDEX", value: {string_value: "0"}} 
parameters: {key: "NUM_THREADS_PER_CORE", value: {string_value: "1"}} 
